### ISSUE TITLE
Encoding `None` does not work in v1.4.0. 

### ISSUE THREAD

**Issue by colin-nolan** [wtsi-hgi/python-json#18]
Issue described by @YuriIvanov in: https://github.com/wtsi-hgi/python-json/issues/16#issuecomment-237527405.

**Comment by colin-nolan** [comment]
The example provided by @YuriIvanov still does not work indicating that this still hasn't been completely fixed!

**Comment by YuriIvanov** [comment]
1.4.1

Traceback (most recent call last):
  File "/Users/RW/testing/workspace/repos/hgijson_test/hgijson_test.py", line 41, in <module>
    main()
  File "/Users/RW/testing/workspace/repos/hgijson_test/hgijson_test.py", line 34, in main
    pprint(json.dumps(user_info, cls=UserInfoJSONEncoder))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/builders.py", line 82, in default
    encoded = superclass.default(encoder, serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/_serialization.py", line 52, in default
    return serializer.serialize(serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/serialization.py", line 54, in serialize
    encoded_value = self._serialize_property_value(value, mapping.serializer_cls)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/serialization.py", line 68, in _serialize_property_value
    return serializer.serialize(to_serialize)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/_converters.py", line 37, in serialize
    return self._encoder.default(serializable)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/hgijson/json/builders.py", line 83, in default
    encoded_combined.update(encoded)
TypeError: 'NoneType' object is not iterable
